// Generated by CoffeeScript 1.6.3
(function() {
  var $;

  $ = jQuery;

  $.FormCheck.i18n = {
    default_language: "en",
    translate: function(path, language) {
      var steps;
      if (language == null) {
        language = $.FormCheck.i18n.default_language;
      }
      steps = path.split(".");
      steps.unshift(language);
      return $.FormCheck.i18n.translation_from_path(steps);
    },
    translation_from_path: function(steps) {
      var current, step, _i, _len;
      current = $.FormCheck.i18n.languages;
      for (_i = 0, _len = steps.length; _i < _len; _i++) {
        step = steps[_i];
        current = current[step];
        if (current == null) {
          return "";
        }
      }
      return current;
    },
    languages: {}
  };

}).call(this);
